# Generated by Django 5.2.7 on 2025-11-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('isi_berita', models.TextField()),
                ('gambar', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('isi_komentar', models.TextField()),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='berita.berita')),
            ],
        ),
    ]
