# Generated by Django 5.2.7 on 2025-11-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
