# Generated by Django 5.2.7 on 2025-10-29 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrasi',
            name='tanggal_registrasi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
