# Generated by Django 5.2.7 on 2025-10-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('telp', models.CharField(max_length=20, unique=True)),
                ('nim', models.IntegerField(unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_mahasiswa/')),
            ],
        ),
    ]
