# Generated by Django 5.2.3 on 2025-10-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_transaksi', models.CharField(max_length=50)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('saldo_akhir', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='tabungan.buku')),
            ],
        ),
    ]
