# Generated by Django 5.2.7 on 2025-10-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0002_transaksi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='saldo_akhir',
            new_name='saldo_akhir_credit',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldo_akhir_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='jenis_transaksi',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
